//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Operaciones
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Contraseña { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
